services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: digitadist
      POSTGRES_USER: postgres     
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: digitadist
  #   ports:
  #     - "8080:80" # Acceso en http://localhost:8080
  #   depends_on:
  #     - db

volumes:
  postgres_data: